/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import {useMutation} from 'react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from 'react-query';

import type {
  PostAuthSignIn200,
  PostAuthSignIn400,
  PostAuthSignIn401,
  PostAuthSignIn422,
  PostAuthSignIn500,
  PostAuthSignInBody,
  PostAuthSignUp201,
  PostAuthSignUp400,
  PostAuthSignUp409,
  PostAuthSignUp422,
  PostAuthSignUp500,
  PostAuthSignUpBody,
} from '.././models';

import {axiosInstance} from '../../axios';
import type {ErrorType, BodyType} from '../../axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Realiza o login do usuário utilizando email e senha, retornando o token de acesso
 * @summary Login do usuário
 */
export const postAuthSignIn = (
  postAuthSignInBody: BodyType<PostAuthSignInBody>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PostAuthSignIn200>(
    {
      url: `/auth/sign-in`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: postAuthSignInBody,
      signal,
    },
    options,
  );
};

export const getPostAuthSignInMutationOptions = <
  TError = ErrorType<
    | PostAuthSignIn400
    | PostAuthSignIn401
    | PostAuthSignIn422
    | PostAuthSignIn500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthSignIn>>,
    TError,
    {data: BodyType<PostAuthSignInBody>},
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthSignIn>>,
  TError,
  {data: BodyType<PostAuthSignInBody>},
  TContext
> => {
  const mutationKey = ['postAuthSignIn'];
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthSignIn>>,
    {data: BodyType<PostAuthSignInBody>}
  > = props => {
    const {data} = props ?? {};

    return postAuthSignIn(data, requestOptions);
  };

  return {mutationFn, ...mutationOptions};
};

export type PostAuthSignInMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthSignIn>>
>;
export type PostAuthSignInMutationBody = BodyType<PostAuthSignInBody>;
export type PostAuthSignInMutationError = ErrorType<
  PostAuthSignIn400 | PostAuthSignIn401 | PostAuthSignIn422 | PostAuthSignIn500
>;

/**
 * @summary Login do usuário
 */
export const usePostAuthSignIn = <
  TError = ErrorType<
    | PostAuthSignIn400
    | PostAuthSignIn401
    | PostAuthSignIn422
    | PostAuthSignIn500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthSignIn>>,
    TError,
    {data: BodyType<PostAuthSignInBody>},
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthSignIn>>,
  TError,
  {data: BodyType<PostAuthSignInBody>},
  TContext
> => {
  const mutationOptions = getPostAuthSignInMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Cria uma nova conta de usuário no sistema com os dados fornecidos
 * @summary Cadastro de novo usuário
 */
export const postAuthSignUp = (
  postAuthSignUpBody: BodyType<PostAuthSignUpBody>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PostAuthSignUp201>(
    {
      url: `/auth/sign-up`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: postAuthSignUpBody,
      signal,
    },
    options,
  );
};

export const getPostAuthSignUpMutationOptions = <
  TError = ErrorType<
    | PostAuthSignUp400
    | PostAuthSignUp409
    | PostAuthSignUp422
    | PostAuthSignUp500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthSignUp>>,
    TError,
    {data: BodyType<PostAuthSignUpBody>},
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthSignUp>>,
  TError,
  {data: BodyType<PostAuthSignUpBody>},
  TContext
> => {
  const mutationKey = ['postAuthSignUp'];
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthSignUp>>,
    {data: BodyType<PostAuthSignUpBody>}
  > = props => {
    const {data} = props ?? {};

    return postAuthSignUp(data, requestOptions);
  };

  return {mutationFn, ...mutationOptions};
};

export type PostAuthSignUpMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthSignUp>>
>;
export type PostAuthSignUpMutationBody = BodyType<PostAuthSignUpBody>;
export type PostAuthSignUpMutationError = ErrorType<
  PostAuthSignUp400 | PostAuthSignUp409 | PostAuthSignUp422 | PostAuthSignUp500
>;

/**
 * @summary Cadastro de novo usuário
 */
export const usePostAuthSignUp = <
  TError = ErrorType<
    | PostAuthSignUp400
    | PostAuthSignUp409
    | PostAuthSignUp422
    | PostAuthSignUp500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthSignUp>>,
    TError,
    {data: BodyType<PostAuthSignUpBody>},
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthSignUp>>,
  TError,
  {data: BodyType<PostAuthSignUpBody>},
  TContext
> => {
  const mutationOptions = getPostAuthSignUpMutationOptions(options);

  return useMutation(mutationOptions);
};
