/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Papel do usuário no sistema
 */
export type GetAuthSession200Role =
  (typeof GetAuthSession200Role)[keyof typeof GetAuthSession200Role];


export const GetAuthSession200Role = {
  customer: 'customer',
  admin: 'admin',
  professional: 'professional',
  supplier: 'supplier',
} as const;
