/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetCouponsId200Type} from './getCouponsId200Type';

export type GetCouponsId200 = {
  id?: number;
  code?: string;
  description?: string;
  type?: GetCouponsId200Type;
  value?: number;
  minOrderValue?: number;
  maxUses?: number;
  usesCount?: number;
  maxUsesPerUser?: number;
  validFrom?: string;
  validUntil?: string;
  active?: boolean;
  supplierId?: number;
  categoryId?: number;
  createdAt?: string;
  updatedAt?: string;
};
