/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetCouponsVerifyCode404Errors} from './getCouponsVerifyCode404Errors';

export type GetCouponsVerifyCode404 = {
  message?: string;
  errors?: GetCouponsVerifyCode404Errors;
};
