/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetCategories200Item = {
  /** ID único da categoria */
  id?: number;
  /** Nome da categoria */
  name?: string;
  /** Descrição da categoria */
  description?: string;
  /**
   * ID da categoria pai
   * @nullable
   */
  categoryId?: number | null;
  /** URL completa da imagem da categoria */
  image?: string;
  /** Data de criação */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
