/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetCouponsVerifyCode422Errors} from './getCouponsVerifyCode422Errors';

export type GetCouponsVerifyCode422 = {
  message?: string;
  errors?: GetCouponsVerifyCode422Errors;
};
