/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetCouponsId200Type =
  (typeof GetCouponsId200Type)[keyof typeof GetCouponsId200Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCouponsId200Type = {
  percent: 'percent',
  fixed: 'fixed',
  shipping: 'shipping',
} as const;
