/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetCouponsParams = {
  /**
   * Filtro de busca por código do cupom (case insensitive)
   */
  query?: string;
  /**
   * Filtrar apenas cupons ativos
   */
  active?: boolean;
  /**
   * Filtrar por ID da categoria
   */
  categoryId?: number;
  /**
   * Filtrar por ID do fornecedor
   */
  supplierId?: number;
};
