/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Categoria pai (se existir)
 * @nullable
 */
export type GetCategoriesId200Category = {
  id?: number;
  name?: string;
  description?: string;
} | null;
