/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetCouponsVerifyCode200Type} from './getCouponsVerifyCode200Type';

export type GetCouponsVerifyCode200 = {
  /** ID único do cupom */
  id?: number;
  /** Código do cupom */
  code?: string;
  /** Descrição do cupom */
  description?: string;
  /** Tipo do desconto */
  type?: GetCouponsVerifyCode200Type;
  /** Valor mínimo do pedido para usar o cupom */
  minOrderValue?: number;
  /** ID do fornecedor associado */
  supplierId?: number;
  /** ID da categoria associada */
  categoryId?: number;
  /** Valor do desconto (percentual ou fixo) */
  value?: number;
  /** Máximo de usos do cupom */
  maxUses?: number;
  /** Quantidade de vezes que o cupom foi usado */
  usesCount?: number;
  /** Máximo de usos por usuário */
  maxUsesPerUser?: number;
  /** Data de início da validade */
  validFrom?: string;
  /** Data de fim da validade */
  validUntil?: string;
  /** Status de ativação do cupom */
  active?: boolean;
  /** Data de criação do cupom */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
