/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo do desconto
 */
export type GetCouponsVerifyCode200Type =
  (typeof GetCouponsVerifyCode200Type)[keyof typeof GetCouponsVerifyCode200Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCouponsVerifyCode200Type = {
  percent: 'percent',
  fixed: 'fixed',
  shipping: 'shipping',
} as const;
