/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetCategoriesId200Category} from './getCategoriesId200Category';

export type GetCategoriesId200 = {
  id?: number;
  name?: string;
  description?: string;
  /** @nullable */
  categoryId?: number | null;
  image?: string;
  /**
   * Categoria pai (se existir)
   * @nullable
   */
  category?: GetCategoriesId200Category;
  createdAt?: string;
  updatedAt?: string;
};
