/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo do desconto
 */
export type GetCoupons200ItemType =
  (typeof GetCoupons200ItemType)[keyof typeof GetCoupons200ItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCoupons200ItemType = {
  percent: 'percent',
  fixed: 'fixed',
  shipping: 'shipping',
} as const;
