/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetNotifications200OrderSharesItem } from './getNotifications200OrderSharesItem';

export type GetNotifications200 = {
  /** Lista de pedidos compartilhados não visualizados */
  orderShares?: GetNotifications200OrderSharesItem[];
};
