/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetNotifications200OrderSharesItem = {
  /** ID único do compartilhamento */
  id?: number;
  /** ID do pedido compartilhado */
  orderId?: number;
  /** ID do usuário que compartilhou */
  sharedByUserId?: number;
  /** ID do usuário que recebeu o compartilhamento */
  sharedWithUserId?: number;
  /** Se a notificação foi visualizada */
  viewed?: boolean;
  /** Mensagem do compartilhamento */
  message?: string;
  /** Data de criação da notificação */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
