/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrderShippings200DataItem = {
  orderId?: number;
  userId?: number;
  price?: number;
  provider?: string;
  shippingCode?: string;
  address?: string;
  city?: string;
  state?: string;
  createdAt?: string;
};
