/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrdersId200UpdatesItem = {
  id?: number;
  status?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  comment?: string | null;
  createdAt?: string;
};
