/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Informações de envio
 * @nullable
 */
export type GetOrdersId200Shipping = {
  id?: number;
  orderId?: number;
  provider?: string;
  /** @nullable */
  shippingCode?: string | null;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  price?: number;
  createdAt?: string;
  updatedAt?: string;
} | null;
