/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrders200Meta = {
  /** Total de registros */
  total?: number;
  /** Registros por página */
  perPage?: number;
  /** Página atual */
  currentPage?: number;
  /** Última página */
  lastPage?: number;
  /** Primeira página */
  firstPage?: number;
  firstPageUrl?: string;
  lastPageUrl?: string;
  /** @nullable */
  nextPageUrl?: string | null;
  /** @nullable */
  previousPageUrl?: string | null;
};
