/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrdersId200Customer} from './getOrdersId200Customer';
import type {GetOrdersId200ItemsItem} from './getOrdersId200ItemsItem';
import type {GetOrdersId200Payment} from './getOrdersId200Payment';
import type {GetOrdersId200Shipping} from './getOrdersId200Shipping';
import type {GetOrdersId200UpdatesItem} from './getOrdersId200UpdatesItem';

export type GetOrdersId200 = {
  id?: number;
  customerId?: number;
  status?: string;
  total?: number;
  /**
   * Dados do cliente (apenas para admins)
   * @nullable
   */
  customer?: GetOrdersId200Customer;
  /** Itens do pedido */
  items?: GetOrdersId200ItemsItem[];
  /**
   * Informações de pagamento
   * @nullable
   */
  payment?: GetOrdersId200Payment;
  /**
   * Informações de envio
   * @nullable
   */
  shipping?: GetOrdersId200Shipping;
  /** Histórico de atualizações do pedido */
  updates?: GetOrdersId200UpdatesItem[];
  createdAt?: string;
  updatedAt?: string;
};
