/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrders200DataItemType = typeof GetOrders200DataItemType[keyof typeof GetOrders200DataItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrders200DataItemType = {
  delivery: 'delivery',
  pickup: 'pickup',
} as const;
