/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrders200DataItemCustomer } from './getOrders200DataItemCustomer';
import type { GetOrders200DataItemPayment } from './getOrders200DataItemPayment';
import type { GetOrders200DataItemShipping } from './getOrders200DataItemShipping';
import type { GetOrders200DataItemLastUpdate } from './getOrders200DataItemLastUpdate';

export type GetOrders200DataItem = {
  id?: number;
  customerId?: number;
  status?: string;
  subtotalPrice?: number;
  totalPrice?: number;
  discountPrice?: number;
  shippingPrice?: number;
  /** @nullable */
  paymentId?: number | null;
  /** @nullable */
  shippingId?: number | null;
  /** Quantidade total de itens */
  itemsCount?: number;
  /**
   * Dados básicos do cliente (apenas para admins)
   * @nullable
   */
  customer?: GetOrders200DataItemCustomer;
  /**
   * Informações básicas de pagamento (se withDetails=true)
   * @nullable
   */
  payment?: GetOrders200DataItemPayment;
  /**
   * Informações básicas de envio (se withDetails=true)
   * @nullable
   */
  shipping?: GetOrders200DataItemShipping;
  /**
   * Última atualização do pedido (se withDetails=true)
   * @nullable
   */
  lastUpdate?: GetOrders200DataItemLastUpdate;
  createdAt?: string;
  updatedAt?: string;
};
