/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrderPaymentsId200ProductsSold} from './getOrderPaymentsId200ProductsSold';
import type {GetOrderPaymentsId200ItemsItem} from './getOrderPaymentsId200ItemsItem';
import type {GetOrderPaymentsId200Order} from './getOrderPaymentsId200Order';

export type GetOrderPaymentsId200 = {
  id?: number;
  orderId?: number;
  paymentMethod?: string;
  status?: string;
  price?: number;
  grossAmount?: number;
  discountAmount?: number;
  netAmount?: number;
  totalItemsCount?: number;
  productsSold?: GetOrderPaymentsId200ProductsSold;
  items?: GetOrderPaymentsId200ItemsItem[];
  order?: GetOrderPaymentsId200Order;
  createdAt?: string;
};
