/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dados básicos do pedido
 */
export type GetOrderShippings200DataItemOrder = {
  id?: number;
  customerId?: number;
  status?: string;
  totalPrice?: number;
};
