/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrderPayments200DataItemItemsItemItemProduct } from './getOrderPayments200DataItemItemsItemItemProduct';

export type GetOrderPayments200DataItemItemsItemItem = {
  product?: GetOrderPayments200DataItemItemsItemItemProduct;
};
