/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrderUpdatesId200Order} from './getOrderUpdatesId200Order';

export type GetOrderUpdatesId200 = {
  id?: number;
  orderId?: number;
  status?: string;
  title?: string;
  comment?: string;
  private?: boolean;
  onlyMe?: boolean;
  order?: GetOrderUpdatesId200Order;
  createdAt?: string;
  updatedAt?: string;
};
