/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrderUpdates200DataItem} from './getOrderUpdates200DataItem';
import type {GetOrderUpdates200Meta} from './getOrderUpdates200Meta';

export type GetOrderUpdates200 = {
  data?: GetOrderUpdates200DataItem[];
  meta?: GetOrderUpdates200Meta;
};
