/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dados do cliente (apenas para admins)
 * @nullable
 */
export type GetOrdersId200Customer = {
  id?: number;
  name?: string;
  email?: string;
} | null;
