/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrderPaymentsId200ItemsItemItemProduct } from './getOrderPaymentsId200ItemsItemItemProduct';

export type GetOrderPaymentsId200ItemsItemItem = {
  product?: GetOrderPaymentsId200ItemsItemItemProduct;
};
