/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersId200ItemsItemProduct } from './getOrdersId200ItemsItemProduct';

export type GetOrdersId200ItemsItem = {
  id?: number;
  orderId?: number;
  productId?: number;
  /** @nullable */
  productVariantId?: number | null;
  quantity?: number;
  unitPrice?: number;
  totalPrice?: number;
  /** Dados completos do produto */
  product?: GetOrdersId200ItemsItemProduct;
  createdAt?: string;
  updatedAt?: string;
};
