/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dados da variante do produto (se houver)
 * @nullable
 */
export type GetOrders200DataItemItemsItemVariant = { [key: string]: unknown } | null;
