/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrderPaymentsIdAnalytics200PaymentDetails = {
  method?: string;
  gateway?: string;
  processingTime?: number;
  currency?: string;
};
