/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Informações básicas de envio (se withDetails=true)
 * @nullable
 */
export type GetOrders200DataItemShipping = {
  orderId?: number;
  provider?: string;
  /** @nullable */
  shippingCode?: string | null;
  city?: string;
  state?: string;
  price?: number;
} | null;
