/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dados básicos do cliente (apenas para admins)
 * @nullable
 */
export type GetOrders200DataItemCustomer = {
  id?: number;
  name?: string;
  email?: string;
} | null;
