/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Última atualização do pedido (se withDetails=true)
 * @nullable
 */
export type GetOrders200DataItemLastUpdate = {
  status?: string;
  title?: string;
  createdAt?: string;
} | null;
