/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrdersId200Type = typeof GetOrdersId200Type[keyof typeof GetOrdersId200Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersId200Type = {
  delivery: 'delivery',
  pickup: 'pickup',
} as const;
