/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetOrdersOrderIdActivityLogs200ItemMetadata = {
  [key: string]: unknown;
} | null;
