/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrdersOrderIdActivityLogs200ItemUser} from './getOrdersOrderIdActivityLogs200ItemUser';
import type {GetOrdersOrderIdActivityLogs200ItemMetadata} from './getOrdersOrderIdActivityLogs200ItemMetadata';

export type GetOrdersOrderIdActivityLogs200Item = {
  id?: number;
  orderId?: number;
  /** @nullable */
  user?: GetOrdersOrderIdActivityLogs200ItemUser;
  action?: string;
  entityType?: string;
  /** @nullable */
  entityId?: number | null;
  /** @nullable */
  oldStatus?: string | null;
  /** @nullable */
  newStatus?: string | null;
  description?: string;
  /** @nullable */
  metadata?: GetOrdersOrderIdActivityLogs200ItemMetadata;
  createdAt?: string;
};
