/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrderShippingsParams = {
/**
 * Filtrar por ID do pedido
 */
orderId?: number;
/**
 * Número da página
 * @minimum 1
 */
page?: number;
/**
 * Itens por página
 * @minimum 1
 * @maximum 100
 */
perPage?: number;
/**
 * Filtrar por transportadora
 */
provider?: string;
};
