/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrderUpdates200DataItem = {
  id?: number;
  orderId?: number;
  status?: string;
  title?: string;
  comment?: string;
  private?: boolean;
  onlyMe?: boolean;
  createdAt?: string;
};
