/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Informações de envio
 * @nullable
 */
export type GetOrdersId200Shipping = {
  id?: number;
  address?: string;
  city?: string;
  /** @nullable */
  trackingCode?: string | null;
} | null;
