/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrderPaymentsId200ItemsItemItem} from './getOrderPaymentsId200ItemsItemItem';

export type GetOrderPaymentsId200ItemsItem = {
  id?: number;
  quantity?: number;
  unitPrice?: number;
  totalPrice?: number;
  item?: GetOrderPaymentsId200ItemsItemItem;
};
