/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrders200DataItemItemsItemProduct } from './getOrders200DataItemItemsItemProduct';
import type { GetOrders200DataItemItemsItemVariant } from './getOrders200DataItemItemsItemVariant';

export type GetOrders200DataItemItemsItem = {
  id?: number;
  orderId?: number;
  productId?: number;
  /** @nullable */
  productVariantId?: number | null;
  quantity?: number;
  unitPrice?: number;
  totalPrice?: number;
  /** Dados completos do produto */
  product?: GetOrders200DataItemItemsItemProduct;
  /**
   * Dados da variante do produto (se houver)
   * @nullable
   */
  variant?: GetOrders200DataItemItemsItemVariant;
  createdAt?: string;
  updatedAt?: string;
};
