/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrderPayments200DataItemItemsItemItem} from './getOrderPayments200DataItemItemsItemItem';

export type GetOrderPayments200DataItemItemsItem = {
  id?: number;
  quantity?: number;
  unitPrice?: number;
  totalPrice?: number;
  item?: GetOrderPayments200DataItemItemsItemItem;
};
