/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrdersOrderIdActivityLogsParams = {
/**
 * Número máximo de logs a retornar
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
