/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrderPaymentsIdAnalytics200ProductsSummaryProductsSold} from './getOrderPaymentsIdAnalytics200ProductsSummaryProductsSold';
import type {GetOrderPaymentsIdAnalytics200ProductsSummaryItemsBreakdownItem} from './getOrderPaymentsIdAnalytics200ProductsSummaryItemsBreakdownItem';

export type GetOrderPaymentsIdAnalytics200ProductsSummary = {
  totalItems?: number;
  productsSold?: GetOrderPaymentsIdAnalytics200ProductsSummaryProductsSold;
  itemsBreakdown?: GetOrderPaymentsIdAnalytics200ProductsSummaryItemsBreakdownItem[];
};
