/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Informações de pagamento
 * @nullable
 */
export type GetOrdersId200Payment = {
  id?: number;
  orderId?: number;
  status?: string;
  paymentMethod?: string;
  price?: number;
  paymentProvider?: string;
  createdAt?: string;
  updatedAt?: string;
} | null;
