/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrderUpdates200Meta = {
  total?: number;
  perPage?: number;
  currentPage?: number;
  lastPage?: number;
};
