/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrders200DataItem} from './getOrders200DataItem';
import type {GetOrders200Meta} from './getOrders200Meta';

export type GetOrders200 = {
  data?: GetOrders200DataItem[];
  meta?: GetOrders200Meta;
};
