/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrderPaymentsStatus =
  (typeof GetOrderPaymentsStatus)[keyof typeof GetOrderPaymentsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrderPaymentsStatus = {
  pending: 'pending',
  processing: 'processing',
  paid: 'paid',
  failed: 'failed',
  refunded: 'refunded',
  cancelled: 'cancelled',
} as const;
