/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetOrderShippings200DataItem} from './getOrderShippings200DataItem';

export type GetOrderShippings200 = {
  data?: GetOrderShippings200DataItem[];
};
