/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Informações de pagamento
 * @nullable
 */
export type GetOrdersId200Payment = {
  id?: number;
  method?: string;
  status?: string;
  amount?: number;
} | null;
