/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrders200DataItem = {
  id?: number;
  customerId?: number;
  status?: string;
  total?: number;
  createdAt?: string;
  updatedAt?: string;
};
