/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Informações básicas de pagamento (se withDetails=true)
 * @nullable
 */
export type GetOrders200DataItemPayment = {
  id?: number;
  orderId?: number;
  status?: string;
  paymentMethod?: string;
  price?: number;
  paymentProvider?: string;
} | null;
