/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrderPayments200DataItemItemsItem } from './getOrderPayments200DataItemItemsItem';

export type GetOrderPayments200DataItem = {
  id?: number;
  orderId?: number;
  paymentMethod?: string;
  status?: string;
  price?: number;
  grossAmount?: number;
  netAmount?: number;
  totalItemsCount?: number;
  items?: GetOrderPayments200DataItemItemsItem[];
};
