/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersId200ItemsItemProduct } from './getOrdersId200ItemsItemProduct';

export type GetOrdersId200ItemsItem = {
  id?: number;
  productId?: number;
  orderId?: number;
  quantity?: number;
  price?: number;
  product?: GetOrdersId200ItemsItemProduct;
};
