/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetOrderShippingsId200ActivityLogsItem = {
  id?: number;
  orderShippingId?: number;
  status?: string;
  title?: string;
  comment?: string;
  createdAt?: string;
};
