/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrderShippingsId200ActivityLogsItem } from './getOrderShippingsId200ActivityLogsItem';

export type GetOrderShippingsId200 = {
  orderId?: number;
  userId?: number;
  price?: number;
  provider?: string;
  shippingCode?: string;
  address?: string;
  number?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  district?: string;
  /** @nullable */
  complement?: string | null;
  /** Logs de atividade do envio */
  activityLogs?: GetOrderShippingsId200ActivityLogsItem[];
  createdAt?: string;
};
