/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dados completos do produto pai
 */
export type GetProductVariantsId200Product = {
  id?: number;
  name?: string;
  description?: string;
  category?: string;
  brand?: string;
  createdAt?: string;
};
