/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetProducts200DataItemSupplier } from './getProducts200DataItemSupplier';
import type { GetProducts200DataItemVariantsItem } from './getProducts200DataItemVariantsItem';
import type { GetProducts200DataItemImagesItem } from './getProducts200DataItemImagesItem';

export type GetProducts200DataItem = {
  id?: number;
  name?: string;
  price?: number;
  description?: string;
  supplierId?: number;
  categoryId?: number;
  /** @nullable */
  tags?: string[] | null;
  stock?: number;
  createdAt?: string;
  updatedAt?: string;
  supplier?: GetProducts200DataItemSupplier;
  variants?: GetProducts200DataItemVariantsItem[];
  images?: GetProducts200DataItemImagesItem[];
};
