/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dados do produto pai
 */
export type GetProductVariants200ItemProduct = {
  id?: number;
  name?: string;
  description?: string;
};
