/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetProductsId200Category} from './getProductsId200Category';
import type {GetProductsId200Supplier} from './getProductsId200Supplier';
import type {GetProductsId200VariantsItem} from './getProductsId200VariantsItem';
import type {GetProductsId200ImagesItem} from './getProductsId200ImagesItem';

export type GetProductsId200 = {
  id?: number;
  name?: string;
  price?: number;
  description?: string;
  supplierId?: number;
  categoryId?: number;
  /** @nullable */
  tags?: string[] | null;
  stock?: number;
  category?: GetProductsId200Category;
  supplier?: GetProductsId200Supplier;
  variants?: GetProductsId200VariantsItem[];
  images?: GetProductsId200ImagesItem[];
  createdAt?: string;
  updatedAt?: string;
};
