/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetProductVariantTypesId200VariantsItem } from './getProductVariantTypesId200VariantsItem';

export type GetProductVariantTypesId200 = {
  /** ID único do tipo de variante */
  id?: number;
  /** Nome do tipo de variante */
  name?: string;
  /** Unidade padrão para este tipo */
  defaultUnit?: string;
  /** Lista de variantes que usam este tipo */
  variants?: GetProductVariantTypesId200VariantsItem[];
  /** Data de criação */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
