/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetProductVariants200ItemProduct} from './getProductVariants200ItemProduct';
import type {GetProductVariants200ItemType} from './getProductVariants200ItemType';

export type GetProductVariants200Item = {
  /** ID único da variante */
  id?: number;
  /** ID do produto pai */
  productId?: number;
  /** ID do tipo de variante */
  variantTypeId?: number;
  /** Valor da variante */
  value?: string;
  /** Unidade de medida */
  unit?: string;
  /** Preço da variante */
  price?: number;
  /** Nome do arquivo da imagem */
  photo?: string;
  /** Dados do produto pai */
  product?: GetProductVariants200ItemProduct;
  /** Tipo da variante */
  type?: GetProductVariants200ItemType;
  /** Data de criação */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
