/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetProfile200AddressesItem = {
  /** ID único do endereço */
  id?: number;
  /** ID do usuário proprietário */
  userId?: number;
  /** Nome do endereço (ex Casa, Trabalho) */
  name?: string;
  /** Nome da rua/logradouro */
  streetName?: string;
  /** Número do endereço */
  number?: string;
  /**
   * Complemento do endereço
   * @nullable
   */
  complement?: string | null;
  /** Bairro */
  neighborhood?: string;
  /** Cidade */
  city?: string;
  /** Estado */
  state?: string;
  /** CEP */
  zipCode?: string;
  /** País */
  country?: string;
  /** Data de criação do endereço */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
