/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Papel do usuário no sistema
 */
export type GetProfile200Role =
  (typeof GetProfile200Role)[keyof typeof GetProfile200Role];


export const GetProfile200Role = {
  customer: 'customer',
  admin: 'admin',
  professional: 'professional',
  supplier: 'supplier',
} as const;
