/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetProductsParams = {
  /**
   * Termo de busca (nome ou descrição)
   */
  query?: string;
  /**
   * Filtrar por categoria
   */
  categoryId?: number;
  /**
   * Número da página
   */
  page?: number;
  /**
   * Itens por página
   */
  perPage?: number;
  /**
   * Agrupar resultados por categoria
   */
  groupByCategory?: boolean;
};
