/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetProductVariantsParams = {
  /**
   * Filtrar por ID do produto
   */
  productId?: number;
  /**
   * Filtrar por tipo de variante
   */
  variantTypeId?: number;
  /**
   * Filtrar por valor da variante
   */
  value?: string;
};
