/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetProductVariantTypesParams = {
/**
 * Filtrar por nome do tipo
 */
name?: string;
/**
 * Filtrar por unidade padrão
 */
defaultUnit?: string;
};
