/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetProductVariantsId200Product} from './getProductVariantsId200Product';
import type {GetProductVariantsId200Type} from './getProductVariantsId200Type';

export type GetProductVariantsId200 = {
  /** ID único da variante */
  id?: number;
  /** ID do produto pai */
  productId?: number;
  /** ID do tipo de variante */
  variantTypeId?: number;
  /** Valor da variante */
  value?: string;
  /** Unidade de medida */
  unit?: string;
  /** Preço da variante */
  price?: number;
  /** Nome do arquivo da imagem */
  photo?: string;
  /** Dados completos do produto pai */
  product?: GetProductVariantsId200Product;
  /** Dados do tipo da variante */
  type?: GetProductVariantsId200Type;
  /** Data de criação da variante */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
