/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetProductVariantTypesId200VariantsItem = {
  id?: number;
  productId?: number;
  value?: string;
  unit?: string;
  price?: number;
  photo?: string;
  createdAt?: string;
};
