/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetProducts200DataItemVariantsItemType } from './getProducts200DataItemVariantsItemType';

export type GetProducts200DataItemVariantsItem = {
  id?: number;
  variantTypeId?: number;
  value?: string;
  /** @nullable */
  unit?: string | null;
  price?: number;
  /** @nullable */
  photo?: string | null;
  type?: GetProducts200DataItemVariantsItemType;
};
