/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetProducts200DataItem} from './getProducts200DataItem';
import type {GetProducts200Meta} from './getProducts200Meta';

export type GetProducts200 = {
  data?: GetProducts200DataItem[];
  meta?: GetProducts200Meta;
};
