/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dados do tipo da variante
 */
export type GetProductVariantsId200Type = {
  id?: number;
  name?: string;
  defaultUnit?: string;
  createdAt?: string;
};
