/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetProfile200Role } from './getProfile200Role';
import type { GetProfile200AddressesItem } from './getProfile200AddressesItem';

export type GetProfile200 = {
  /** ID único do usuário */
  id?: number;
  /**
   * Nome completo do usuário
   * @nullable
   */
  name?: string | null;
  /**
   * Nome de usuário único
   * @nullable
   */
  username?: string | null;
  /** Email do usuário */
  email?: string;
  /** Papel do usuário no sistema */
  role?: GetProfile200Role;
  /**
   * URL completa do avatar do usuário
   * @nullable
   */
  avatar?: string | null;
  /** Número de telefone formatado */
  phoneNumber?: string;
  /** Data de criação do usuário */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
  /** Lista de endereços do usuário */
  addresses?: GetProfile200AddressesItem[];
};
