/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo da variante
 */
export type GetProductVariants200ItemType = {
  id?: number;
  name?: string;
  defaultUnit?: string;
};
