/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetProductVariantTypes200ItemVariantsItem} from './getProductVariantTypes200ItemVariantsItem';

export type GetProductVariantTypes200Item = {
  /** ID único do tipo de variante */
  id?: number;
  /** Nome do tipo de variante */
  name?: string;
  /** Unidade padrão para este tipo */
  defaultUnit?: string;
  /** Variantes relacionadas a este tipo */
  variants?: GetProductVariantTypes200ItemVariantsItem[];
  /** Data de criação */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
