/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetProductsId200VariantsItemType} from './getProductsId200VariantsItemType';

export type GetProductsId200VariantsItem = {
  id?: number;
  variantTypeId?: number;
  value?: string;
  /** @nullable */
  unit?: string | null;
  price?: number;
  /** @nullable */
  photo?: string | null;
  type?: GetProductsId200VariantsItemType;
};
