/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetSuppliersSortOrder = typeof GetSuppliersSortOrder[keyof typeof GetSuppliersSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSuppliersSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
