/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetSuppliers200Meta } from './getSuppliers200Meta';
import type { GetSuppliers200DataItem } from './getSuppliers200DataItem';

export type GetSuppliers200 = {
  meta?: GetSuppliers200Meta;
  data?: GetSuppliers200DataItem[];
};
