/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetSuppliers200Meta = {
  total?: number;
  per_page?: number;
  current_page?: number;
  last_page?: number;
  first_page?: number;
  first_page_url?: string;
  last_page_url?: string;
  /** @nullable */
  next_page_url?: string | null;
  /** @nullable */
  previous_page_url?: string | null;
};
