/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetSuppliersSortBy} from './getSuppliersSortBy';
import type {GetSuppliersSortOrder} from './getSuppliersSortOrder';

export type GetSuppliersParams = {
  /**
   * Número da página para paginação
   */
  page?: number;
  /**
   * Número de itens por página
   */
  limit?: number;
  /**
   * Termo de busca para filtrar por nome ou descrição
   */
  search?: string;
  /**
   * Campo para ordenação
   */
  sortBy?: GetSuppliersSortBy;
  /**
   * Ordem de classificação
   */
  sortOrder?: GetSuppliersSortOrder;
};
