/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetSuppliersSortBy =
  (typeof GetSuppliersSortBy)[keyof typeof GetSuppliersSortBy];


export const GetSuppliersSortBy = {
  name: 'name',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const;
