/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetSuppliers200DataItem = {
  /** ID único do fornecedor */
  id?: number;
  /** Nome do fornecedor */
  name?: string;
  /** Descrição do fornecedor */
  description?: string;
  /** Endereço do fornecedor */
  address?: string;
  /**
   * URL completa da foto do fornecedor
   * @nullable
   */
  photo?: string | null;
  /** ID do proprietário do fornecedor */
  ownerId?: number;
  /** Data de criação */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
