/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dados limitados retornados para usuários não-admin
 */
export type GetUsers200DataItemOneOfThree = {
  /** ID único do usuário */
  id?: number;
  /**
   * Nome completo do usuário
   * @nullable
   */
  name?: string | null;
  /**
   * URL completa do avatar do usuário
   * @nullable
   */
  avatar?: string | null;
  /**
   * Nome de usuário único
   * @nullable
   */
  username?: string | null;
};
