/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type GetUsers200Meta = {
  /** Total de registros */
  total?: number;
  /** Registros por página */
  perPage?: number;
  /** Página atual */
  currentPage?: number;
  /** Última página */
  lastPage?: number;
  /** Primeira página */
  firstPage?: number;
  /** URL da primeira página */
  firstPageUrl?: string;
  /** URL da última página */
  lastPageUrl?: string;
  /**
   * URL da próxima página
   * @nullable
   */
  nextPageUrl?: string | null;
  /**
   * URL da página anterior
   * @nullable
   */
  previousPageUrl?: string | null;
};
