/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Papel do usuário no sistema
 */
export type GetUsers200DataItemOneOfRole =
  (typeof GetUsers200DataItemOneOfRole)[keyof typeof GetUsers200DataItemOneOfRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUsers200DataItemOneOfRole = {
  customer: 'customer',
  admin: 'admin',
  professional: 'professional',
  supplier: 'supplier',
} as const;
