/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {GetUsersUserIdActivityLogs200ItemOrder} from './getUsersUserIdActivityLogs200ItemOrder';

export type GetUsersUserIdActivityLogs200Item = {
  id?: number;
  orderId?: number;
  order?: GetUsersUserIdActivityLogs200ItemOrder;
  action?: string;
  description?: string;
  createdAt?: string;
};
