/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsers200DataItemOneOfRole } from './getUsers200DataItemOneOfRole';

/**
 * Dados completos retornados para usuários admin
 */
export type GetUsers200DataItemOneOf = {
  /** ID único do usuário */
  id?: number;
  /**
   * Nome completo do usuário
   * @nullable
   */
  name?: string | null;
  /**
   * Nome de usuário único
   * @nullable
   */
  username?: string | null;
  /** Email do usuário */
  email?: string;
  /** Papel do usuário no sistema */
  role?: GetUsers200DataItemOneOfRole;
  /**
   * URL completa do avatar do usuário
   * @nullable
   */
  avatar?: string | null;
  /**
   * Número de telefone formatado
   * @nullable
   */
  phoneNumber?: string | null;
  /** Data de criação do usuário */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
