/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PatchOrderSharesViewBody = {
  /** ID do compartilhamento a ser marcado como visualizado */
  orderShareId: string;
};
