/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PatchOrderSharesView200 = {
  /** ID único do compartilhamento */
  id?: string;
  /** ID do pedido compartilhado */
  orderId?: number;
  /** ID do usuário que compartilhou */
  userId?: number;
  /** ID do usuário que recebeu o compartilhamento */
  sharedWithUserId?: number;
  /** Status de visualização (sempre true após esta operação) */
  viewed?: boolean;
  /** Data de criação do compartilhamento */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
