/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Novo status do pedido
 */
export type PostOrderUpdatesBodyStatus =
  (typeof PostOrderUpdatesBodyStatus)[keyof typeof PostOrderUpdatesBodyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrderUpdatesBodyStatus = {
  Pending: 'Pending',
  Confirmed: 'Confirmed',
  Processing: 'Processing',
  On_Hold: 'On Hold',
  Awaiting_Payment: 'Awaiting Payment',
  Payment_Received: 'Payment Received',
  In_Production: 'In Production',
  Shipped: 'Shipped',
  Out_for_Delivery: 'Out for Delivery',
  Delivered: 'Delivered',
  Completed: 'Completed',
  Cancelled: 'Cancelled',
  Refunded: 'Refunded',
  Failed: 'Failed',
  Returned: 'Returned',
  Partially_Shipped: 'Partially Shipped',
  Backordered: 'Backordered',
} as const;
