/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostAuthSignUp201UserRole} from './postAuthSignUp201UserRole';

export type PostAuthSignUp201User = {
  /** ID único do usuário */
  id?: number;
  /** Nome completo do usuário */
  name?: string;
  /** Email do usuário */
  email?: string;
  /** Nome de usuário único */
  username?: string;
  /** Papel do usuário no sistema */
  role?: PostAuthSignUp201UserRole;
  /** Data de criação do usuário */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
