/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostProductVariantsBody = {
  /** ID do produto pai */
  productId: number;
  /** ID do tipo de variante (ex. cor, tamanho) */
  variantTypeId: number;
  /** Valor da variante (ex. "Azul", "M", "64GB") */
  value: string;
  /** Unidade de medida (opcional) */
  unit?: string;
  /**
   * Preço específico desta variante
   * @minimum 0.01
   */
  price: number;
  /** Imagem da variante (JPG, JPEG, PNG - máx 2MB) */
  photo: Blob;
};
