/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthSignUp201User } from './postAuthSignUp201User';
import type { PostAuthSignUp201Token } from './postAuthSignUp201Token';

export type PostAuthSignUp201 = {
  user?: PostAuthSignUp201User;
  token?: PostAuthSignUp201Token;
};
