/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostAuthSignUp409Errors} from './postAuthSignUp409Errors';

export type PostAuthSignUp409 = {
  message?: string;
  errors?: PostAuthSignUp409Errors;
};
