/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Papel do usuário no sistema
 */
export type PostAuthSignIn200UserRole =
  (typeof PostAuthSignIn200UserRole)[keyof typeof PostAuthSignIn200UserRole];


export const PostAuthSignIn200UserRole = {
  customer: 'customer',
  admin: 'admin',
  professional: 'professional',
  supplier: 'supplier',
} as const;
