/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PostProducts201VariantsItem } from './postProducts201VariantsItem';

export type PostProducts201 = {
  id?: number;
  name?: string;
  price?: number;
  description?: string;
  supplierId?: number;
  categoryId?: number;
  tags?: string[];
  stock?: number;
  createdAt?: string;
  updatedAt?: string;
  variants?: PostProducts201VariantsItem[];
};
