/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostProductsBodyVariantsItem = {
  /** ID do tipo de variante */
  variantTypeId: number;
  /** Valor da variante */
  value: string;
  /** Unidade (opcional) */
  unit?: string;
  /** Preço específico da variante */
  price: number;
  /** Foto específica da variante */
  photo?: Blob;
};
