/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostOrdersOrderIdActivityLogs201 = {
  id?: number;
  orderId?: number;
  action?: string;
  description?: string;
  createdAt?: string;
  message?: string;
};
