/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostOrderSharesShareBody = {
  /** ID do pedido a ser compartilhado */
  orderId: number;
  /** ID do usuário que receberá o compartilhamento */
  sharedWithUserId: number;
};
