/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostOrdersOrderIdActivityLogsBodyMetadata} from './postOrdersOrderIdActivityLogsBodyMetadata';

export type PostOrdersOrderIdActivityLogsBody = {
  /** Ação realizada */
  action: string;
  /** Descrição da atividade */
  description: string;
  /** Dados adicionais (opcional) */
  metadata?: PostOrdersOrderIdActivityLogsBodyMetadata;
};
