/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PostProductVariants422Errors } from './postProductVariants422Errors';

export type PostProductVariants422 = {
  message?: string;
  errors?: PostProductVariants422Errors;
};
