/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthSignIn200User } from './postAuthSignIn200User';
import type { PostAuthSignIn200Token } from './postAuthSignIn200Token';

export type PostAuthSignIn200 = {
  user?: PostAuthSignIn200User;
  token?: PostAuthSignIn200Token;
};
