/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostOrdersBodyItemsItem} from './postOrdersBodyItemsItem';
import type {PostOrdersBodyType} from './postOrdersBodyType';

export type PostOrdersBody = {
  /** Itens do pedido */
  items: PostOrdersBodyItemsItem[];
  /** ID do endereço de entrega (opcional) */
  addressId?: number;
  /** Tipo do pedido - entrega ou retirada */
  type?: PostOrdersBodyType;
};
