/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Papel do usuário no sistema
 */
export type PostAuthSignUp201UserRole = typeof PostAuthSignUp201UserRole[keyof typeof PostAuthSignUp201UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthSignUp201UserRole = {
  customer: 'customer',
  admin: 'admin',
  professional: 'professional',
  supplier: 'supplier',
} as const;
