/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostAuthSignUp400Errors} from './postAuthSignUp400Errors';

export type PostAuthSignUp400 = {
  message?: string;
  errors?: PostAuthSignUp400Errors;
};
