/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostProducts201 = {
  id?: number;
  name?: string;
  price?: number;
  description?: string;
  supplierId?: number;
  categoryId?: number;
  tags?: string[];
  stock?: number;
  createdAt?: string;
};
