/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PostProductsBodyVariantsItem } from './postProductsBodyVariantsItem';

export type PostProductsBody = {
  /** Nome do produto */
  name: string;
  /**
   * Preço do produto
   * @minimum 0.01
   */
  price: number;
  /** Descrição detalhada do produto */
  description: string;
  /** ID do fornecedor */
  supplierId: number;
  /** ID da categoria */
  categoryId: number;
  /** Tags separadas por vírgula */
  tags?: string;
  /**
   * Quantidade em estoque
   * @minimum 0
   */
  stock?: number;
  /** Imagem principal do produto (PNG, JPG, JPEG - máx 2MB) */
  image: Blob;
  /** Imagens adicionais do produto */
  images?: Blob[];
  /** Variantes do produto (ex. cores, tamanhos) */
  variants?: PostProductsBodyVariantsItem[];
};
