/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostOrders201Type = typeof PostOrders201Type[keyof typeof PostOrders201Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrders201Type = {
  delivery: 'delivery',
  pickup: 'pickup',
} as const;
