/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostAuthSignUp422Errors} from './postAuthSignUp422Errors';

export type PostAuthSignUp422 = {
  message?: string;
  errors?: PostAuthSignUp422Errors;
};
