/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostOrderUpdates201 = {
  /** ID único da atualização */
  id?: number;
  /** ID do pedido atualizado */
  orderId?: number;
  /** Status aplicado ao pedido */
  status?: string;
  /**
   * Título da atualização
   * @nullable
   */
  title?: string | null;
  /**
   * Comentário da atualização
   * @nullable
   */
  comment?: string | null;
  /**
   * Se é uma atualização privada
   * @nullable
   */
  private?: boolean | null;
  /**
   * Se é visível apenas para o criador
   * @nullable
   */
  onlyMe?: boolean | null;
  /** Data de criação da atualização */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
