/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostProductVariantTypesBody = {
  /**
   * Nome do tipo de variante
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * Unidade padrão para este tipo
   * @minLength 1
   * @maxLength 20
   */
  defaultUnit: string;
};
