/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PostCouponsBodyType } from './postCouponsBodyType';

export type PostCouponsBody = {
  /** Código único do cupom (será convertido para maiúsculo) */
  code: string;
  /** Descrição do cupom */
  description: string;
  /** Tipo do desconto */
  type: PostCouponsBodyType;
  /**
   * Valor do desconto (percentual de 0-100 para percent, valor fixo para fixed/shipping)
   * @minimum 0
   */
  value: number;
  /**
   * Valor mínimo do pedido para usar o cupom
   * @minimum 0
   */
  minOrderValue?: number;
  /**
   * Máximo de usos do cupom
   * @minimum 1
   */
  maxUses: number;
  /**
   * Máximo de usos por usuário
   * @minimum 1
   */
  maxUsesPerUser?: number;
  /** Data de início da validade */
  validFrom: string;
  /** Data de fim da validade */
  validUntil: string;
  /** Status de ativação do cupom */
  active?: boolean;
  /** ID do fornecedor associado (opcional) */
  supplierId?: number;
  /** ID da categoria associada (opcional) */
  categoryId?: number;
};
