/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostAuthSignUpBodyTwoRole} from './postAuthSignUpBodyTwoRole';

export type PostAuthSignUpBodyTwo = {
  /**
   * Nome completo do usuário
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** Email único do usuário */
  email: string;
  /**
   * Nome de usuário único
   * @minLength 3
   * @maxLength 50
   * @pattern ^[a-zA-Z0-9._-]+$
   */
  username: string;
  /**
   * Senha do usuário
   * @minLength 8
   */
  password: string;
  /** Papel do usuário no sistema */
  role: PostAuthSignUpBodyTwoRole;
  /**
   * Número de telefone brasileiro
   * @pattern ^[0-9]{10,11}$
   */
  phoneNumber?: string;
};
