/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostOrdersBodyItemsItem = {
  /** ID do produto */
  product_id: number;
  /** ID da variante do produto (opcional) */
  product_variant_id?: number;
  /**
   * Quantidade do produto
   * @minimum 1
   */
  quantity: number;
  /** Preço unitário do produto no momento da compra */
  unit_price: number;
};
