/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthSignInBody = {
  /** Email do usuário */
  email: string;
  /**
   * Senha do usuário
   * @minLength 6
   */
  password: string;
};
