/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostCategories201 = {
  id?: number;
  name?: string;
  description?: string;
  /** @nullable */
  categoryId?: number | null;
  image?: string;
  createdAt?: string;
  updatedAt?: string;
};
