/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PostOrders201ItemsItemProduct } from './postOrders201ItemsItemProduct';

export type PostOrders201ItemsItem = {
  id?: number;
  orderId?: number;
  productId?: number;
  /** @nullable */
  productVariantId?: number | null;
  quantity?: number;
  unitPrice?: number;
  totalPrice?: number;
  /** Dados completos do produto */
  product?: PostOrders201ItemsItemProduct;
  createdAt?: string;
  updatedAt?: string;
};
