/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostOrdersBodyPaymentMethod} from './postOrdersBodyPaymentMethod';

/**
 * Informações de pagamento
 */
export type PostOrdersBodyPayment = {
  /** Método de pagamento */
  method?: PostOrdersBodyPaymentMethod;
  /**
   * Número de parcelas
   * @minimum 1
   */
  installments?: number;
};
