/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostProductVariantTypes422Errors} from './postProductVariantTypes422Errors';

export type PostProductVariantTypes422 = {
  message?: string;
  errors?: PostProductVariantTypes422Errors;
};
