/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostProductVariantTypes201 = {
  /** ID único do tipo de variante */
  id?: number;
  /** Nome do tipo de variante */
  name?: string;
  /** Unidade padrão para este tipo */
  defaultUnit?: string;
  createdAt?: string;
  updatedAt?: string;
};
