/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostProducts422Errors} from './postProducts422Errors';

export type PostProducts422 = {
  message?: string;
  errors?: PostProducts422Errors;
};
