/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Método de envio
 */
export type PostOrdersBodyShippingMethod =
  (typeof PostOrdersBodyShippingMethod)[keyof typeof PostOrdersBodyShippingMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrdersBodyShippingMethod = {
  standard: 'standard',
  express: 'express',
  same_day: 'same_day',
} as const;
