/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Método de pagamento
 */
export type PostOrdersBodyPaymentMethod =
  (typeof PostOrdersBodyPaymentMethod)[keyof typeof PostOrdersBodyPaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrdersBodyPaymentMethod = {
  credit_card: 'credit_card',
  debit_card: 'debit_card',
  pix: 'pix',
  bank_transfer: 'bank_transfer',
} as const;
