/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostOrdersBodyShippingMethod} from './postOrdersBodyShippingMethod';

/**
 * Informações de envio
 */
export type PostOrdersBodyShipping = {
  /** Endereço de entrega */
  address?: string;
  /** Cidade */
  city?: string;
  /** Estado */
  state?: string;
  /** CEP */
  zipCode?: string;
  /** Método de envio */
  method?: PostOrdersBodyShippingMethod;
};
