/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Papel do usuário no sistema
 */
export type PostAuthSignUpBodyOneRole =
  (typeof PostAuthSignUpBodyOneRole)[keyof typeof PostAuthSignUpBodyOneRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthSignUpBodyOneRole = {
  customer: 'customer',
  admin: 'admin',
  professional: 'professional',
  supplier: 'supplier',
} as const;
