/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostSuppliers400ErrorsItem} from './postSuppliers400ErrorsItem';

export type PostSuppliers400 = {
  message?: string;
  errors?: PostSuppliers400ErrorsItem[];
};
