/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostUserAddressesBody = {
  /** Nome/apelido para identificar o endereço */
  name: string;
  /** Nome da rua, avenida, etc. */
  streetName: string;
  /** Número da residência/estabelecimento */
  number: string;
  /** Complemento (apartamento, sala, bloco, etc.) */
  complement?: string;
  /** Bairro */
  neighborhood: string;
  /** Cidade */
  city: string;
  /** Estado (sigla) */
  state: string;
  /** CEP (com ou sem formatação) */
  zipCode: string;
  /** País */
  country?: string;
};
