/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostCategories400Errors} from './postCategories400Errors';

export type PostCategories400 = {
  message?: string;
  errors?: PostCategories400Errors;
};
