/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostAuthSignIn422Errors} from './postAuthSignIn422Errors';

export type PostAuthSignIn422 = {
  message?: string;
  errors?: PostAuthSignIn422Errors;
};
