/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostOrderUpdates400Errors} from './postOrderUpdates400Errors';

export type PostOrderUpdates400 = {
  message?: string;
  errors?: PostOrderUpdates400Errors;
};
