/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostAuthSignUpBodyOneRole} from './postAuthSignUpBodyOneRole';

export type PostAuthSignUpBodyOne = {
  /**
   * Nome completo do usuário
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** Email único do usuário */
  email: string;
  /**
   * Nome de usuário único (apenas letras, números, pontos, hífens e underscores)
   * @minLength 3
   * @maxLength 50
   * @pattern ^[a-zA-Z0-9._-]+$
   */
  username: string;
  /**
   * Senha do usuário (mínimo 8 caracteres, deve conter ao menos uma letra maiúscula, uma minúscula, um número e um caractere especial)
   * @minLength 8
   */
  password: string;
  /** Papel do usuário no sistema */
  role: PostAuthSignUpBodyOneRole;
  /**
   * Número de telefone brasileiro (10 ou 11 dígitos, sem código do país)
   * @pattern ^[0-9]{10,11}$
   */
  phoneNumber?: string;
  /** Arquivo de imagem para avatar (JPG, PNG ou JPEG, máximo 2MB) */
  avatar?: Blob;
};
