/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostUserAddresses201 = {
  /** ID único do endereço criado */
  id?: number;
  /** ID do usuário proprietário */
  userId?: number;
  name?: string;
  streetName?: string;
  number?: string;
  /** @nullable */
  complement?: string | null;
  neighborhood?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
  createdAt?: string;
  updatedAt?: string;
};
