/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Papel do usuário no sistema
 */
export type PostAuthSignUpBodyTwoRole =
  (typeof PostAuthSignUpBodyTwoRole)[keyof typeof PostAuthSignUpBodyTwoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthSignUpBodyTwoRole = {
  customer: 'customer',
  admin: 'admin',
  professional: 'professional',
  supplier: 'supplier',
} as const;
