/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type PostOrders201Shipping = {[key: string]: unknown} | null;
