/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostOrderUpdates422Errors} from './postOrderUpdates422Errors';

export type PostOrderUpdates422 = {
  message?: string;
  errors?: PostOrderUpdates422Errors;
};
