/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostProductVariants201 = {
  /** ID único da variante */
  id?: number;
  /** ID do produto pai */
  productId?: number;
  /** ID do tipo de variante */
  variantTypeId?: number;
  /** Valor da variante */
  value?: string;
  /**
   * Unidade de medida
   * @nullable
   */
  unit?: string | null;
  /** Preço da variante */
  price?: number;
  /** Nome do arquivo da imagem */
  photo?: string;
  createdAt?: string;
  updatedAt?: string;
};
