/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo do desconto
 */
export type PostCouponsBodyType =
  (typeof PostCouponsBodyType)[keyof typeof PostCouponsBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCouponsBodyType = {
  percent: 'percent',
  fixed: 'fixed',
  shipping: 'shipping',
} as const;
