/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthSignIn200Token = {
  /** Tipo do token */
  type?: string;
  /** Nome do token */
  name?: string;
  /** Hash do token para autenticação */
  token?: string;
  /** Permissões associadas ao token */
  abilities?: string[];
  /**
   * Data do último uso do token
   * @nullable
   */
  lastUsedAt?: string | null;
  /**
   * Data de expiração do token
   * @nullable
   */
  expiresAt?: string | null;
};
