/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PostSuppliersBody = {
  /**
   * Nome do fornecedor
   * @minLength 3
   */
  name: string;
  /** Descrição do fornecedor */
  description?: string;
  /**
   * Endereço do fornecedor
   * @minLength 10
   */
  address: string;
  /** Foto do fornecedor (PNG, JPG, JPEG - máx 4MB) */
  photo?: Blob;
};
