/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PostOrders201Type } from './postOrders201Type';
import type { PostOrders201ItemsItem } from './postOrders201ItemsItem';

export type PostOrders201 = {
  id?: number;
  customerId?: number;
  status?: string;
  type?: PostOrders201Type;
  subtotalPrice?: number;
  totalPrice?: number;
  discountPrice?: number;
  shippingPrice?: number;
  /** @nullable */
  paymentId?: number | null;
  /** @nullable */
  shippingId?: number | null;
  /** @nullable */
  couponId?: number | null;
  items?: PostOrders201ItemsItem[];
  createdAt?: string;
  updatedAt?: string;
};
