/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo do pedido - entrega ou retirada
 */
export type PostOrdersBodyType =
  (typeof PostOrdersBodyType)[keyof typeof PostOrdersBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrdersBodyType = {
  delivery: 'delivery',
  pickup: 'pickup',
} as const;
