/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostAuthSignIn400Errors} from './postAuthSignIn400Errors';

export type PostAuthSignIn400 = {
  message?: string;
  errors?: PostAuthSignIn400Errors;
};
