/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostOrders201ItemsItem} from './postOrders201ItemsItem';
import type {PostOrders201Payment} from './postOrders201Payment';
import type {PostOrders201Shipping} from './postOrders201Shipping';

export type PostOrders201 = {
  id?: number;
  customerId?: number;
  status?: string;
  total?: number;
  items?: PostOrders201ItemsItem[];
  /** @nullable */
  payment?: PostOrders201Payment;
  /** @nullable */
  shipping?: PostOrders201Shipping;
  createdAt?: string;
  updatedAt?: string;
};
