/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostUserAddresses422Errors} from './postUserAddresses422Errors';

export type PostUserAddresses422 = {
  message?: string;
  errors?: PostUserAddresses422Errors;
};
