/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PostOrderUpdatesBodyStatus} from './postOrderUpdatesBodyStatus';

export type PostOrderUpdatesBody = {
  /** ID do pedido a ser atualizado */
  orderId: number;
  /** Novo status do pedido */
  status: PostOrderUpdatesBodyStatus;
  /** Título da atualização */
  title?: string;
  /** Comentário adicional sobre a atualização */
  comment?: string;
  /** Se a atualização é privada (não visível para o cliente) */
  private?: boolean;
  /** Se a atualização é visível apenas para quem criou */
  onlyMe?: boolean;
};
