/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PutCategoriesIdBody = {
  /**
   * Nome da categoria
   * @minLength 3
   */
  name: string;
  /** Descrição da categoria */
  description?: string;
  /** ID da categoria pai */
  categoryId?: number;
  /** Nova imagem da categoria (PNG, JPG, JPEG - máx 4MB) */
  image: Blob;
};
