/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PutCategoriesId200 = {
  id?: number;
  name?: string;
  description?: string;
  categoryId?: number;
  image?: string;
  createdAt?: string;
  updatedAt?: string;
};
