/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo do desconto
 */
export type PutCouponsIdBodyType =
  (typeof PutCouponsIdBodyType)[keyof typeof PutCouponsIdBodyType];


export const PutCouponsIdBodyType = {
  percent: 'percent',
  fixed: 'fixed',
  shipping: 'shipping',
} as const;
