/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Novo status do pagamento
 */
export type PutOrderPaymentsIdUpdateStatusBodyStatus =
  (typeof PutOrderPaymentsIdUpdateStatusBodyStatus)[keyof typeof PutOrderPaymentsIdUpdateStatusBodyStatus];


export const PutOrderPaymentsIdUpdateStatusBodyStatus = {
  pending: 'pending',
  processing: 'processing',
  paid: 'paid',
  failed: 'failed',
  refunded: 'refunded',
  cancelled: 'cancelled',
} as const;
