/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PutOrderShippingsIdBody = {
  /** Preço do envio */
  price?: number;
  /** Transportadora */
  provider?: string;
  /** Código de rastreamento */
  shippingCode?: string;
  /** Endereço de entrega */
  address?: string;
  /** Número do endereço */
  number?: string;
  /** Cidade */
  city?: string;
  /** Estado */
  state?: string;
  /** CEP */
  zipCode?: string;
  /** Bairro */
  district?: string;
  /**
   * Complemento do endereço
   * @nullable
   */
  complement?: string | null;
};
