/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PutOrderPaymentsIdUpdateStatusBodyStatus } from './putOrderPaymentsIdUpdateStatusBodyStatus';

export type PutOrderPaymentsIdUpdateStatusBody = {
  /** Novo status do pagamento */
  status: PutOrderPaymentsIdUpdateStatusBodyStatus;
  /** Comentário sobre a mudança de status */
  comment?: string;
};
