/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PutProfile422Errors} from './putProfile422Errors';

export type PutProfile422 = {
  message?: string;
  errors?: PutProfile422Errors;
};
