/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PutProductsId200VariantsItem} from './putProductsId200VariantsItem';

export type PutProductsId200 = {
  id?: number;
  name?: string;
  price?: number;
  description?: string;
  supplierId?: number;
  categoryId?: number;
  /** @nullable */
  tags?: string[] | null;
  stock?: number;
  createdAt?: string;
  updatedAt?: string;
  variants?: PutProductsId200VariantsItem[];
};
