/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PutProductsIdBody = {
  /** Nome do produto */
  name: string;
  /**
   * Novo preço do produto
   * @minimum 0.01
   */
  price: number;
  /** Nova descrição do produto */
  description: string;
  /** ID do fornecedor */
  supplierId: number;
  /** ID da categoria */
  categoryId: number;
  /**
   * Lista de tags
   * @nullable
   */
  tags?: string[] | null;
  /**
   * Quantidade em estoque
   * @minimum 0
   */
  stock?: number;
};
