/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PutProductVariantTypesId422Errors} from './putProductVariantTypesId422Errors';

export type PutProductVariantTypesId422 = {
  message?: string;
  errors?: PutProductVariantTypesId422Errors;
};
