/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PutProductsId200VariantsItemType } from './putProductsId200VariantsItemType';

export type PutProductsId200VariantsItem = {
  id?: number;
  variantTypeId?: number;
  value?: string;
  /** @nullable */
  unit?: string | null;
  price?: number;
  /** @nullable */
  photo?: string | null;
  type?: PutProductsId200VariantsItemType;
};
