/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PutProductVariantsIdBody = {
  /** ID do tipo de variante */
  variantTypeId: number;
  /** Novo valor da variante */
  value: string;
  /** Unidade de medida (opcional) */
  unit?: string;
  /**
   * Novo preço da variante
   * @minimum 0.01
   */
  price: number;
  /** Nova imagem da variante (JPG, JPEG, PNG - máx 2MB) - opcional */
  photo?: Blob;
};
