/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

/**
 * Papel do usuário no sistema
 */
export type PutProfile200Role = typeof PutProfile200Role[keyof typeof PutProfile200Role];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutProfile200Role = {
  customer: 'customer',
  admin: 'admin',
  professional: 'professional',
  supplier: 'supplier',
} as const;
