/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PutProductVariantsId422Errors} from './putProductVariantsId422Errors';

export type PutProductVariantsId422 = {
  message?: string;
  errors?: PutProductVariantsId422Errors;
};
