/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PutProductVariantTypesId200 = {
  id?: number;
  name?: string;
  defaultUnit?: string;
  createdAt?: string;
  updatedAt?: string;
};
