/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PutProfile400Errors } from './putProfile400Errors';

export type PutProfile400 = {
  message?: string;
  errors?: PutProfile400Errors;
};
