/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PutProductsId422Errors } from './putProductsId422Errors';

export type PutProductsId422 = {
  message?: string;
  errors?: PutProductsId422Errors;
};
