/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type {PutProfile200Role} from './putProfile200Role';

export type PutProfile200 = {
  /** ID único do usuário */
  id?: number;
  /** Nome completo do usuário */
  name?: string;
  /** Nome de usuário único */
  username?: string;
  /** Email do usuário */
  email?: string;
  /** Papel do usuário no sistema */
  role?: PutProfile200Role;
  /**
   * URL completa do avatar do usuário
   * @nullable
   */
  avatar?: string | null;
  /** Número de telefone formatado */
  phoneNumber?: string;
  /** Data de criação do usuário */
  createdAt?: string;
  /** Data da última atualização */
  updatedAt?: string;
};
