/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PutProductVariantsId200 = {
  id?: number;
  productId?: number;
  variantTypeId?: number;
  value?: string;
  /** @nullable */
  unit?: string | null;
  price?: number;
  /** Nome do arquivo da imagem (atualizada ou existente) */
  photo?: string;
  createdAt?: string;
  updatedAt?: string;
};
