/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */
import type { PutSuppliersId400ErrorsItem } from './putSuppliersId400ErrorsItem';

export type PutSuppliersId400 = {
  message?: string;
  errors?: PutSuppliersId400ErrorsItem[];
};
