/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Simbora API
 * Documentação da API Simbora
 * OpenAPI spec version: 1.0.0
 */

export type PutSuppliersId200 = {
  id?: number;
  name?: string;
  description?: string;
  address?: string;
  /** @nullable */
  photo?: string | null;
  ownerId?: number;
  createdAt?: string;
  updatedAt?: string;
};
