export const PROFESSIONAL_TYPES = [
  'Eletricista',
  'Encanador',
  'Pedreiro',
  'Pintor',
  'Gesseiro',
  'Carpinteiro',
  'Marceneiro',
  'Serralheiro',
  'Vidraceiro',
  'Azulejista',
  'Marmorista',
  'Instalador de Pisos',
  'Instalador de Forro',
  'Instalador de Ar Condicionado',
  'Técnico em Refrigeração',
  'Soldador',
  'Mestre de Obras',
  'Arquiteto',
  'Engenheiro Civil',
  'Topógrafo',
  'Jardineiro',
  'Paisagista',
  'Impermeabilizador',
  'Dedetizador',
  'Limpeza e Conservação',
  'Chaveiro',
  'Porteiro',
  'Vigilante',
  'Armador',
  'Ferreiro',
  'Outros',
] as const;

export type ProfessionalType = typeof PROFESSIONAL_TYPES[number];
